# -*- coding: utf-8 -*-
"""ch08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CNeLsHwASQnNO-4aBdbDJpFqnvzQKyxk
"""

f = open("new_note.txt",'w')
f.close

# writedata.py
f = open("new_not.txt", 'w')
for i in range(1, 11):
    data = "%d번째 줄입니다.\n" % i
    f.write(data)
f.close()

f = open("foo.txt","w")
f.write("Life is too short, you need python")
f.close()

with open("foo.txt","w") as f:
  f.write("Life is too short, you need python")

"""#점프 투 파이썬 복습"""

languages = ['pytjon','perl','c','java']
for lang in languages:
  if lang in ['python','perl']:
    print("%6s need interpreter" %lang )
  elif lang in ['c','java']:
    print("%6s need compiler" %lang)
  else:
    print("should not reach here")

"""Life is too short, You need python"""

'''Life is too short, You need Python'''

a = "Life is too short, You need Python"

print(a.split())

b = a.split()

b[1]

a = [1,2,3]
a.append(4)
a

a = [1,2,3]
b = (1,2,3)
c = str(a) +str(b)

type(c)

a = [1,2,3,4,5]
a.insert(3,6)
a

a.remove(6)
a

a=[1,2,3]
a.pop(1)
print(a)

t1 = (1,2,3,4,5)
t2 = (1)
t3 = (1,)
print(type(t2),type(t3))

type(t1[0:1])

dic = {'name':'pey','phone':'0102388471', "birth" : "1020201"}

dic

